[project]
name = "localdeepresearch-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-adk>=1.5.0",
    "google-genai>=1.24.0",
    "python-dotenv>=1.1.1",
]
